Preselime/Models/Shared/ItemList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preselime.Models.Shared
{
    public class ItemList
    {
        public int Id { get; set; }
        public String Name { get; set; }
    }
}

Preselime/Controllers/LoginController.cs
using Preselime.Models.Login;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Preselime.Builders;
using Preselime.Models.User;
using Domain;

namespace Preselime.Controllers
{
    public class LoginController : Controller
    {
        preselimeEntities db;

        public LoginController()
        {
            db = new preselimeEntities();
        }
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel login)
        {
            if (ModelState.IsValid)
            {
                UserModel user = LoginBuilder.Login(login, db);
                if (user != null)
                {
                    if(user.UserTypeId == 1)
                    {
                        Session["CarrierLogedIn"] = user;
                        return RedirectToAction("Index","SenderDashboard");
                    }
                    else {
                        Session["SenderLogedIn"] = user;
                        return RedirectToAction("Index", "SenderDashboard");
                    }
                }
                else
                {
                    ViewBag.Message = "Logovanje nije uspelo";
                }
            }
            return View("Index");
        }
    }
}

Preselime/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Preselime.Models.Register;

namespace Preselime.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SenderRegistration()
        {
            
            return View("SenderRegistration");
        }
        [HttpPost]
        public ActionResult CarrierRegister(RegistrationCarrierModel model)
        {
            if (ModelState.IsValid)
            {

            }
            return View("SenderRegistration");
        }
    }
}

Preselime/Controllers/ShipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Preselime.Models.Shipment;
using Preselime.Builders;

namespace Preselime.Controllers

{
    public class ShipmentController : Controller
    {
        preselimeEntities db;

        public ShipmentController()
        {
            db = new preselimeEntities();
        }
        // GET: Shipment
        public ActionResult Index()
        {
            ShipmentModel shipmentModel = ShipmentBuilder.GetShipmentList(db);
            return View(shipmentModel);
        }

        // GET: Shipment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Shipment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shipment/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Shipment/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Shipment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Shipment/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Shipment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Preselime/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="">
                    <img style="width:200px;padding-top:15px;" src="~/Content/ui/logo.png" />
                </a>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Pronadji oglas", "Index", "Shipment")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Ulogujte se", "Index", "Login")</li>
                    <li>@Html.ActionLink("Registracija", "Index", "Register")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top:20px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Preselime</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Preselime/Views/Shared/_LogedInLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="">
                    <img style="width:200px;padding-top:15px;" src="~/Content/ui/logo.png" />
                </a>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Pronadji oglas", "Index", "Shipment")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Moj profil", "Index", "SenderDashboard")</li>
                    <li>@Html.ActionLink("Izloguj me", "Index", "Register")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top:20px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Preselime</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>